name: skd1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_spinkit: ^5.2.1
  get_storage: ^2.1.1
  get: ^4.6.6  
  intl: 0.19.0
  google_fonts: ^6.2.1
  date_picker_timeline: ^1.2.6
  timezone: ^0.10.0
  sqflite: ^2.4.2 
  path: ^1.8.3
  flutter_staggered_animations: ^1.1.1
  flutter_local_notifications: ^19.2.1
  flutter_timezone: ^4.1.1
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  avatar_glow: ^3.0.1  # Mikrofon animasyonu için
  http: ^1.4.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/mini_proje_resim.jpg
    - assets/apple1.png
    - assets/profile.png
    - assets/photo.png
    - assets/user-photo.png
